version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/airbnb
      SPRING_DATASOURCE_USERNAME: airbnb_usr
      SPRING_DATASOURCE_PASSWORD: SecureAccDB
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "app.jar"]

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: SecureAccDB
      MYSQL_DATABASE: airbnb
      MYSQL_USER: airbnb_usr
      MYSQL_PASSWORD: SecureAccDB
    ports:
      - "3306:3306"
